image: node:14

pipelines:
  branches:
    develop:
      - step:
          name: "Install depencies and build"
          script:
            - export NEXT_PUBLIC_API_URL=$DEV_NEXT_PUBLIC_API_URL
            - export BITBUCKET_COMMIT=$BITBUCKET_COMMIT
            - export NODE_ENV=$DEV_NODE_ENV
            - npm install
            - npm run build
          artifacts:
            - .next/**
            - public/**

      - step:
          name: "Zip artifacts for EB"
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r /application.zip ./.
          artifacts:
            - application.zip
          
      - step:
          name: "Deployment to EBS"
          image: atlassian/pipelines-awscli
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                ENVIRONMENT_NAME: $DEV_AWS_EB_ENV_NAME
                APPLICATION_NAME: $AWS_EB_APP_NAME
                ZIP_FILE: "application.zip"
