image: node:14

definitions:
  steps:
    - step: &Build-step
        name: Build App
        script:
          - "apt-get update -y"
          - "apt-get install -y zip"
          - export NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
          - export NODE_ENV=$NODE_ENV
          - npm install
          - npm run build
          - zip -r application.zip . -x bitbucket-pipelines.yml */components/**\* */contexts/**\* */gql/**\* */pages/**\* */styles/**\* */utils/**\* *.git* */node_modules/**\*
        artifacts:
          - application.zip

    - step: &Deploy-step
        name: Deploy to elasticbeanstalk
        image: atlassian/pipelines-awscli
        script:
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: $AWS_BEANSTALK_APPLICATION_NAME
              ENVIRONMENT_NAME: $AWS_BEANSTALK_ENVIRONMENT_NAME
              ZIP_FILE: "application.zip"

pipelines:
  custom:
    deploy-to-staging:
      - step: *Build-step
      - step: *Deploy-step
  branches:
    develop:
      - step: *Build-step
      - step: *Deploy-step